Class {
	#name : 'DebugInfoTest',
	#superclass : 'TestCase',
	#classVars : [
		'ClassVar'
	],
	#category : 'DebugInfo-Tests',
	#package : 'DebugInfo-Tests'
}

{ #category : 'helpers' }
DebugInfoTest >> methodWithArgumentCapturingContext: anArgument [

	"anArgument is unused, but the context should capture it"
	^ thisContext copy
]

{ #category : 'helpers' }
DebugInfoTest >> methodWithArgumentCapturingFullBlockContext: anArgument [

	"anArgument is unused, but the context should capture it"
	^ [  thisContext copy ] value
]

{ #category : 'helpers' }
DebugInfoTest >> methodWithArgumentCapturingOptimizedBlockContext: anArgument [

	"anArgument is unused, but the context should capture it"
	^ true ifTrue: [ thisContext copy ]
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithConstantBlockReturn [

	[ 1 ]
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithDynamicArrayCreation [

	{ 1 + 2 . 17 }
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithFullBlockReturn [

	| stolen |
	[ stolen ]
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithGlobalVariableAssignment [

	ClassVar := #toto
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithImplicitReturn [

	"^ self"
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithInstanceVariableAssignment [

	"Just to test, this code is never executed"
	testSelector := #toto
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithLiterals [

	17 . #asd . 'asd' . 1.77777 . #() . nil . true . false
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithLocalVariableAssignment [

	| local |
	local := #toto
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithOptimizedSend [

	1 to: 3 do: [ :i | 17 + 42 ]
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithReturn [

	^ self
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithSend [

	self yourself
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> methodWithVariableReads [

	| temp |
	
	temp.
	testSelector.
	ClassVar.
	DebugInfoTest
]

{ #category : 'tests - arguments' }
DebugInfoTest >> testBlockArgumentVariableIsArgument [

	| debugInfo context |
	context := [ :blockArgument | thisContext copy ] value: 7.

	debugInfo := OldDebugInfo for: context method.

	self assert: (debugInfo isArgumentNamed: #blockArgument at: context pc)
]

{ #category : 'tests - arguments' }
DebugInfoTest >> testBlockTemporaryVariableIsNotArgument [

	| debugInfo context |
	context := [ :blockArgument | | tempInBlock | thisContext copy ] value: 7.

	debugInfo := OldDebugInfo for: context method.

	self deny: (debugInfo isArgumentNamed: #tempInBlock at: context pc)
]

{ #category : 'tests - listing variables' }
DebugInfoTest >> testDoNotListVariablesDefinedInFollowingNonSurroundingLexicalScopes [

	| debugInfo context |
	
	"We capture the context outside of the if statement.
	Thus, the variable defined inside the conditional block should not be visible"
	context := thisContext copy.
	true ifTrue: [ 
		| inOptimizedScope |  ].

	debugInfo := OldDebugInfo for: context method.

	self
		assert: (debugInfo variableNamesAt: context pc)
		equals: #( debugInfo context )
]

{ #category : 'tests - listing variables' }
DebugInfoTest >> testDoNotListVariablesDefinedInPreviousNonSurroundingLexicalScopes [

	| debugInfo context |
	
	true ifTrue: [ 
		| inOptimizedScope |  ].

	"We capture the context outside of the if statement.
	Thus, the variable defined inside the conditional block should not be visible"
	context := thisContext copy.
	debugInfo := OldDebugInfo for: context method.

	self
		assert: (debugInfo variableNamesAt: context pc)
		equals: #( debugInfo context )
]

{ #category : 'tests - listing variables' }
DebugInfoTest >> testListArguments [

	| debugInfo contextWithArguments |
	contextWithArguments := self methodWithArgumentCapturingContext: 17.
	debugInfo := OldDebugInfo for: contextWithArguments method.

	self
		assert: (debugInfo variableNamesAt: contextWithArguments pc)
		equals: #( anArgument )
]

{ #category : 'tests - listing variables' }
DebugInfoTest >> testListBlockArguments [

	| debugInfo context |
	context := [ :blockArgument | thisContext copy ] value: 7.

	debugInfo := OldDebugInfo for: context method.

	self
		assert: (debugInfo variableNamesAt: context pc)
		equals: #( debugInfo context blockArgument )
]

{ #category : 'tests - listing variables' }
DebugInfoTest >> testListMethodTemps [

	| debugInfo context |
	context := thisContext copy.
	debugInfo := OldDebugInfo for: context method.

	self assert: (debugInfo variableNamesAt: context pc) equals: #(debugInfo context)
]

{ #category : 'tests - listing variables' }
DebugInfoTest >> testListOptimizedBlockArguments [

	| debugInfo context |
	context := self ifNotNil: [ :blockArgument | 
		| inOptimizedScope | 
		"Put an assignment just after the context capture.
		Like this, the captured context PC will be inside the block (at the assignment point).
		Thus, lexically we are inside the block and the variables of the block are visible"
		inOptimizedScope := thisContext copy ].

	debugInfo := OldDebugInfo for: context method.

	self
		assert: (debugInfo variableNamesAt: context pc)
		equals: #( debugInfo context blockArgument inOptimizedScope )
]

{ #category : 'tests - listing variables' }
DebugInfoTest >> testListOuterVariables [

	| debugInfo context |
	context := [ thisContext copy ] value.

	debugInfo := OldDebugInfo for: context method.

	self
		assert: (debugInfo variableNamesAt: context pc)
		equals: #( debugInfo context )
]

{ #category : 'tests - listing variables' }
DebugInfoTest >> testListShadowedVariablesAreNotDuplicated [

	| debugInfo context |
	context := [ "Shadowing!"
		           | debugInfo |
		           debugInfo := 17.
		           thisContext copy ] value.

	debugInfo := OldDebugInfo for: context method.

	self
		assert: (debugInfo variableNamesAt: context pc)
		equals: #( context debugInfo )
]

{ #category : 'tests - listing variables' }
DebugInfoTest >> testListVariablesWithinOptimizedContext [

	| debugInfo context |
	
	context := true ifTrue: [ 
		| inOptimizedScope | 
		"Put an assignment just after the context capture.
		Like this, the captured context PC will be inside the block (at the assignment point).
		Thus, lexically we are inside the block and the variables of the block are visible"
		inOptimizedScope := thisContext copy ].

	debugInfo := OldDebugInfo for: context method.

	self
		assert: (debugInfo variableNamesAt: context pc)
		equals: #( debugInfo context inOptimizedScope )
]

{ #category : 'tests - arguments' }
DebugInfoTest >> testMethodArgumentVariableIsArgument [

	| debugInfo contextWithArguments |
	contextWithArguments := self methodWithArgumentCapturingContext: 17.
	debugInfo := OldDebugInfo for: contextWithArguments method.

	self assert:
		(debugInfo isArgumentNamed: #anArgument at: contextWithArguments pc)
]

{ #category : 'tests - arguments' }
DebugInfoTest >> testMethodTemporaryVariableIsNotArgument [

	| debugInfo contextWithArguments |
	contextWithArguments := thisContext copy.
	debugInfo := OldDebugInfo for: contextWithArguments method.

	self deny: (debugInfo
			 isArgumentNamed: #contextWithArguments
			 at: contextWithArguments pc)
]

{ #category : 'tests - arguments' }
DebugInfoTest >> testNonExistingVariableIsArgumentRaisesError [

	| debugInfo context |
	context := thisContext copy.
	debugInfo := OldDebugInfo for: context method.

	[ debugInfo isArgumentNamed: #notAVariable at: context pc.
		self fail ]
		on: Error
		do: [ :err | 
			self assert: err messageText equals: 'Variable not found: notAVariable' ]
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testNotStopAtAllButFirstBytecodeOfOptimizedSend [

	| debugInfo methodToTest send todoPCs |
	methodToTest := self class >> #methodWithOptimizedSend.
	debugInfo := OldDebugInfo for: methodToTest.

	"a to:do: send should stop at the to:do: point but not in the intermediate steps"
	send := methodToTest ast statements first.
	todoPCs := send methodNode pcsForNode: send.
	self assert: todoPCs size > 1.
	
	todoPCs allButFirst do: [ :otherPC |
		self deny: (debugInfo shouldStopAt: otherPC). ]
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testNotStopAtConstantBlockCreation [

	| debugInfo methodToTest blockNode blockCreationPC |
	methodToTest := self class >> #methodWithConstantBlockReturn.
	debugInfo := OldDebugInfo for: methodToTest.

	blockNode := methodToTest ast statements first.
	blockCreationPC := (blockNode methodNode pcsForNode: blockNode) first.
	
	self deny: (debugInfo shouldStopAt: blockCreationPC)
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testNotStopAtDynamicArrayCreation [

	| debugInfo methodToTest dynamicArrayCreationNode blockCreationPCs |
	methodToTest := self class >> #methodWithDynamicArrayCreation.
	debugInfo := OldDebugInfo for: methodToTest.

	dynamicArrayCreationNode := methodToTest ast statements first.
	blockCreationPCs := dynamicArrayCreationNode methodNode pcsForNode: dynamicArrayCreationNode.
	self assert: blockCreationPCs notEmpty.
	
	blockCreationPCs do: [ :e |
		self deny: (debugInfo shouldStopAt: e). ]
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testNotStopAtFullBlockCreation [

	| debugInfo methodToTest blockNode blockCreationPCs |
	methodToTest := self class >> #methodWithFullBlockReturn.
	debugInfo := OldDebugInfo for: methodToTest.

	blockNode := methodToTest ast statements first.
	"A block may have many PCs: the creation of the block but also the creation of the temp verctor and the copied vars
	None of them are stop points."
	blockCreationPCs := (blockNode methodNode pcsForNode: blockNode).
	self assert: blockCreationPCs notEmpty.
	
	blockCreationPCs do: [ :e |
		self deny: (debugInfo shouldStopAt: e)
	]
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testNotStopAtLiterals [

	| debugInfo methodToTest literalNodes |
	methodToTest := self class >> #methodWithLiterals.
	debugInfo := OldDebugInfo for: methodToTest.

	literalNodes := methodToTest ast statements.
	self assert: literalNodes notEmpty.
	
	literalNodes do: [ :node | | literalPCs |
		"Some literal nodes are eliminated from the bytecode (and others not?)
		Thus, some are mapped and others not.
		
		For our purposes we don't care. If not mapped we will not stop.
		But if mapped, we should not stop on them"
		literalPCs := (node methodNode pcsForNode: node).
		self assert: (literalPCs isEmpty or: [ (debugInfo shouldStopAt: literalPCs first) not ])
	]
	
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testNotStopAtVariableReads [

	| debugInfo methodToTest variableNodes |
	methodToTest := self class >> #methodWithVariableReads.
	debugInfo := OldDebugInfo for: methodToTest.

	variableNodes := methodToTest ast statements.
	self assert: variableNodes notEmpty.
	
	variableNodes do: [ :node | | variableReadPCs |
		"Some variable nodes are eliminated from the bytecode (and others not?)
		Thus, some are mapped and others not.
		
		For our purposes we don't care. If not mapped we will not stop.
		But if mapped, we should not stop on them"
		variableReadPCs := (node methodNode pcsForNode: node).
		self assert: (variableReadPCs isEmpty or: [ (debugInfo shouldStopAt: variableReadPCs first) not ])
	]
	
]

{ #category : 'tests - arguments' }
DebugInfoTest >> testOptimizedBlockArgumentVariableIsArgument [

	| debugInfo context |
	context := self ifNotNil: [ :blockArgument | 
		| inOptimizedScope | 
		"Put an assignment just after the context capture.
		Like this, the captured context PC will be inside the block (at the assignment point).
		Thus, lexically we are inside the block and the variables of the block are visible"
		inOptimizedScope := thisContext copy ].

	debugInfo := OldDebugInfo for: context method.

	self assert: (debugInfo isArgumentNamed: #blockArgument at: context pc)
]

{ #category : 'tests - arguments' }
DebugInfoTest >> testOptimizedBlockTemporaryVariableIsNotArgument [

	| debugInfo context |
	context := self ifNotNil: [ :blockArgument | 
		| inOptimizedScope | 
		"Put an assignment just after the context capture.
		Like this, the captured context PC will be inside the block (at the assignment point).
		Thus, lexically we are inside the block and the variables of the block are visible"
		inOptimizedScope := thisContext copy ].

	debugInfo := OldDebugInfo for: context method.

	self deny: (debugInfo isArgumentNamed: #inOptimizedScope at: context pc)
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadLocalBlockArgumentVariable [

	| debugInfo context |
	context := [ :blockArgument | thisContext copy ] value: 7.

	debugInfo := OldDebugInfo for: context method.

	self assert: (debugInfo readVariableNamed: #blockArgument fromContext: context) equals: 7
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadLocalBlockTempVectorTemporaryVariableFromClosure [

	"This test is tricky.
	
	If done like the other tests (copying and returning the captured context) this breaks the closures.
	The block contexts refer to closures, and each closure refer to its (creator) outer context.
	However, when copying the stack, they point to the original context and not the copy.
	
	Instead of making a transitive closure of the graph copy, let's just put the assertion in the block
	"
	| debugInfo |
	[ :blockArgument |
		| tempInTempVector context |
		tempInTempVector := 42.
		
		"Create and execute a block that steals an enclosing variable"
		"tempInTempVector is assigned in two different lexical contexts.
		It is then candidate to be put in a temp vector, which will be copied in the block activation"	
		[
			tempInTempVector := 3
		] value.
		
		context := thisContext.
		debugInfo := OldDebugInfo for: context method.

		self
			assert: (debugInfo readVariableNamed: #tempInTempVector fromContext: context)
			equals: 3
	] value: 7.
	
	"Verify that the inner block got effectively executed"
	self assert: debugInfo notNil
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadLocalBlockTempVectorTemporaryVariableFromMethod [
	"This test is tricky.
	
	If done like the other tests (copying and returning the captured context) this breaks the closures.
	The block contexts refer to closures, and each closure refer to its (creator) outer context.
	However, when copying the stack, they point to the original context and not the copy.
	
	Instead of making a transitive closure of the graph copy, let's just put the assertion in the block
	"

	| debugInfo tempInTempVector context |
	tempInTempVector := 42.

	"Create and execute a block that steals an enclosing variable"
	"tempInTempVector is assigned in two different lexical contexts.
		It is then candidate to be put in a temp vector, which will be copied in the block activation"
	[ tempInTempVector := 3 ] value.

	context := thisContext.
	debugInfo := OldDebugInfo for: context method.

	self
		assert: (debugInfo readVariableNamed: #tempInTempVector fromContext: context)
		equals: 3
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadLocalBlockTemporaryVariable [

	| debugInfo context |
	context := [ :blockArgument | | tempInBlock | tempInBlock := 42. thisContext copy ] value: 7.

	debugInfo := OldDebugInfo for: context method.

	self assert: (debugInfo readVariableNamed: #tempInBlock fromContext: context) equals: 42
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadLocalMethodArgumentVariable [

	| debugInfo contextWithArguments |
	contextWithArguments := self methodWithArgumentCapturingContext: 17.
	debugInfo := OldDebugInfo for: contextWithArguments method.

	self assert:
		(debugInfo readVariableNamed: #anArgument fromContext: contextWithArguments) equals: 17
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadLocalMethodTemporaryVariable [

	| debugInfo contextWithArguments |
	contextWithArguments := thisContext copy.
	debugInfo := OldDebugInfo for: contextWithArguments method.

	self
		deny: (debugInfo
				 readVariableNamed: #contextWithArguments
				 fromContext: contextWithArguments)
		equals: contextWithArguments
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadLocalOptimizedBlockArgumentVariable [

	| debugInfo context |
	context := self ifNotNil: [ :blockArgument | 
		| inOptimizedScope | 
		"Put an assignment just after the context capture.
		Like this, the captured context PC will be inside the block (at the assignment point).
		Thus, lexically we are inside the block and the variables of the block are visible"
		inOptimizedScope := thisContext copy ].

	debugInfo := OldDebugInfo for: context method.

	self assert: (debugInfo readVariableNamed: #blockArgument fromContext: context) equals: self
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadLocalOptimizedBlockTemporaryVariable [

	| debugInfo context |
	context := self ifNotNil: [ :blockArgument | 
		| inOptimizedScope | 
		"Put an assignment just after the context capture.
		Like this, the captured context PC will be inside the block (at the assignment point).
		Thus, lexically we are inside the block and the variables of the block are visible"
		inOptimizedScope := thisContext copy ].

	debugInfo := OldDebugInfo for: context method.

	self deny: (debugInfo readVariableNamed: #inOptimizedScope fromContext: context) equals: context
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadNonExistingVariableRaisesError [

	| debugInfo context |
	context := thisContext copy.
	debugInfo := OldDebugInfo for: context method.

	[ debugInfo readVariableNamed: #notAVariable fromContext: context.
		self fail ]
		on: Error
		do: [ :err | 
			self assert: err messageText equals: 'Variable not found: notAVariable' ]
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterBlockArgumentVariableFromClosure [

	| debugInfo context |
	context := [ :blockArgument | [thisContext copy] value ] value: 7.

	debugInfo := OldDebugInfo for: context method.

	self assert: (debugInfo readVariableNamed: #blockArgument fromContext: context) equals: 7
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterBlockArgumentVariableFromOptimizedBlock [

	| debugInfo context |
	context := [ :blockArgument | true ifTrue: [thisContext copy] ] value: 7.

	debugInfo := OldDebugInfo for: context method.

	self assert: (debugInfo readVariableNamed: #blockArgument fromContext: context) equals: 7
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterBlockCopiedArgumentVariableFromClosure [

	| debugInfo context |
	context := [ :blockArgument | [ blockArgument. thisContext copy] value ] value: 7.

	debugInfo := OldDebugInfo for: context method.

	self assert: (debugInfo readVariableNamed: #blockArgument fromContext: context) equals: 7
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterBlockCopiedTemporaryVariableFromClosure [

	"This test is tricky.
	
	If done like the other tests (copying and returning the captured context) this breaks the closures.
	The block contexts refer to closures, and each closure refer to its (creator) outer context.
	However, when copying the stack, they point to the original context and not the copy.
	
	Instead of making a transitive closure of the graph copy, let's just put the assertion in the block
	"
	| debugInfo |
	[ :blockArgument |
		| tempInBlock |
		tempInBlock := 42.
		[
			| context |
			"tempInBlock is candidate to be copied in the block activation"
			tempInBlock.

			context := thisContext.
			debugInfo := OldDebugInfo for: context method.

			self
				assert: (debugInfo readVariableNamed: #tempInBlock fromContext: context)
				equals: 42 ] value ] value: 7.
	
	"Verify that the inner block got effectively executed"
	self assert: debugInfo notNil
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterBlockTempVectorTemporaryVariableFromClosure [

	"This test is tricky.
	
	If done like the other tests (copying and returning the captured context) this breaks the closures.
	The block contexts refer to closures, and each closure refer to its (creator) outer context.
	However, when copying the stack, they point to the original context and not the copy.
	
	Instead of making a transitive closure of the graph copy, let's just put the assertion in the block
	"
	| debugInfo |
	[ :blockArgument |
		| tempInTempVector |
		tempInTempVector := 42.
		[
			| context |
			"tempInTempVector is assigned in two different lexical contexts.
			It is then candidate to be put in a temp vector, which will be copied in the block activation"
			tempInTempVector := 3.

			context := thisContext.
			debugInfo := OldDebugInfo for: context method.

			self
				assert: (debugInfo readVariableNamed: #tempInTempVector fromContext: context)
				equals: 3 ] value ] value: 7.
	
	"Verify that the inner block got effectively executed"
	self assert: debugInfo notNil
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterBlockTemporaryVariableFromClosure [

	"This test is tricky.
	
	If done like the other tests (copying and returning the captured context) this breaks the closures.
	The block contexts refer to closures, and each closure refer to its (creator) outer context.
	However, when copying the stack, they point to the original context and not the copy.
	
	Instead of making a transitive closure of the graph copy, let's just put the assertion in the block
	"
	| debugInfo |
	[ :blockArgument |
		| tempInBlock |
		tempInBlock := 42.
		[
			| context |
			context := thisContext.
			debugInfo := OldDebugInfo for: context method.

			self
				assert: (debugInfo readVariableNamed: #tempInBlock fromContext: context)
				equals: 42 ] value ] value: 7.
	
	"Verify that the inner block got effectively executed"
	self assert: debugInfo notNil
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterBlockTemporaryVariableFromOptimizedBlock [

	"This test is tricky.
	
	If done like the other tests (copying and returning the captured context) this breaks the closures.
	The block contexts refer to closures, and each closure refer to its (creator) outer context.
	However, when copying the stack, they point to the original context and not the copy.
	
	Instead of making a transitive closure of the graph copy, let's just put the assertion in the block
	"
	| debugInfo |
	[ :blockArgument |
		| tempInBlock |
		tempInBlock := 42.
		true ifTrue: [
			| context |
			context := thisContext.
			debugInfo := OldDebugInfo for: context method.

			self
				assert: (debugInfo readVariableNamed: #tempInBlock fromContext: context)
				equals: 42 ] ] value: 7.
	
	"Verify that the inner block got effectively executed"
	self assert: debugInfo notNil
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterMethodArgumentVariableFromClosure [

	| debugInfo contextWithArguments |
	contextWithArguments := self methodWithArgumentCapturingFullBlockContext: 17.
	debugInfo := OldDebugInfo for: contextWithArguments method.

	self assert:
		(debugInfo readVariableNamed: #anArgument fromContext: contextWithArguments) equals: 17
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterMethodArgumentVariableFromOptimizedBlock [

	| debugInfo contextWithArguments |
	contextWithArguments := self methodWithArgumentCapturingOptimizedBlockContext: 17.
	debugInfo := OldDebugInfo for: contextWithArguments method.

	self assert:
		(debugInfo readVariableNamed: #anArgument fromContext: contextWithArguments) equals: 17
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterMethodTemporaryVariableFromClosure [

	| debugInfo contextWithArguments |
	contextWithArguments := [thisContext copy] value.
	debugInfo := OldDebugInfo for: contextWithArguments method.

	self
		assert: (debugInfo
				 readVariableNamed: #contextWithArguments
				 fromContext: contextWithArguments)
		equals: contextWithArguments
]

{ #category : 'tests - read variables' }
DebugInfoTest >> testReadOuterMethodTemporaryVariableFromOptimizedBlock [

	| debugInfo contextWithArguments outerVariable |
	outerVariable := 17.
	
	contextWithArguments := true ifTrue: [thisContext copy].
	debugInfo := OldDebugInfo for: contextWithArguments method.

	self
		assert: (debugInfo
				 readVariableNamed: #outerVariable
				 fromContext: contextWithArguments)
		equals: outerVariable
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtConstantBlockReturn [

	| debugInfo methodToTest returnPC blockNode constantBlock |
	methodToTest := self class >> #methodWithConstantBlockReturn.
	constantBlock := methodToTest literalAt: 1.
	debugInfo := OldDebugInfo for: constantBlock compiledBlock.

	"Since the return does not exist in the AST, the block return bytecode is mapped to the block's sequence node (differently than methods)"
	blockNode := methodToTest ast statements first.
	"The return bytecode is the last bytecode of the block"
	returnPC := (blockNode pcsForNode: blockNode body) last.
	
	self assert: (debugInfo shouldStopAt: returnPC).
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtExplicitReturn [

	| debugInfo methodToTest return returnPC |
	methodToTest := self class >> #methodWithReturn.
	debugInfo := OldDebugInfo for: methodToTest.

	return := methodToTest ast statements first.
	returnPC := (return methodNode pcsForNode: return) first.
	
	self assert: (debugInfo shouldStopAt: returnPC).
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtFirstBytecodeOfOptimizedSend [

	| debugInfo methodToTest send sendPC |
	methodToTest := self class >> #methodWithOptimizedSend.
	debugInfo := OldDebugInfo for: methodToTest.

	"a to:do: send should stop at the to:do: point"
	send := methodToTest ast statements first.
	sendPC := (send methodNode pcsForNode: send) first.
	
	self assert: (debugInfo shouldStopAt: sendPC).
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtFullBlockReturn [

	| debugInfo methodToTest returnPC blockNode compiledBlock |
	methodToTest := self class >> #methodWithFullBlockReturn.
	compiledBlock := methodToTest literalAt: 1.
	debugInfo := OldDebugInfo for: compiledBlock.

	"Since the return does not exist in the AST, the block return bytecode is mapped to the block's sequence node (differently than methods).
	This happens because a block node is mapped to its creation!
	However: why we don't map sequences in methods too?"
	blockNode := methodToTest ast statements first.
	"The return bytecode is the last bytecode of the block"
	returnPC := (blockNode pcsForNode: blockNode body) last.
	
	self assert: (debugInfo shouldStopAt: returnPC).
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtGlobalVariableAssignment [

	| debugInfo methodToTest returnPC assignmentNode |
	methodToTest := self class >> #methodWithGlobalVariableAssignment.
	debugInfo := OldDebugInfo for: methodToTest.

	assignmentNode := methodToTest ast statements first.
	returnPC := (assignmentNode methodNode pcsForNode: assignmentNode) first.
	
	self assert: (debugInfo shouldStopAt: returnPC).
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtImplicitMethodReturn [

	| debugInfo methodToTest returnPC methodNode |
	methodToTest := self class >> #methodWithImplicitReturn.
	debugInfo := OldDebugInfo for: methodToTest.

	"Since the return does not exist in the AST, the return bytecode is mapped to the method node"
	methodNode := methodToTest ast.
	"The return bytecode is the last bytecode of the method"
	returnPC := (methodNode pcsForNode: methodNode) last.
	
	self assert: (debugInfo shouldStopAt: returnPC).
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtInstanceVariableAssignment [

	| debugInfo methodToTest returnPC assignmentNode |
	methodToTest := self class >> #methodWithInstanceVariableAssignment.
	debugInfo := OldDebugInfo for: methodToTest.

	assignmentNode := methodToTest ast statements first.
	returnPC := (assignmentNode methodNode pcsForNode: assignmentNode) first.
	
	self assert: (debugInfo shouldStopAt: returnPC).
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtLocalVariableAssignment [

	| debugInfo methodToTest returnPC assignmentNode |
	methodToTest := self class >> #methodWithLocalVariableAssignment.
	debugInfo := OldDebugInfo for: methodToTest.

	assignmentNode := methodToTest ast statements first.
	returnPC := (assignmentNode methodNode pcsForNode: assignmentNode) first.
	
	self assert: (debugInfo shouldStopAt: returnPC).
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtSend [

	| debugInfo methodToTest send sendPC |
	methodToTest := self class >> #methodWithSend.
	debugInfo := OldDebugInfo for: methodToTest.

	send := methodToTest ast statements first.
	sendPC := (send methodNode pcsForNode: send) first.
	
	self assert: (debugInfo shouldStopAt: sendPC).
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtSendInDynamicArray [

	| debugInfo methodToTest dynamicArrayNode sendInsideDynamicArrayNode sendPC |
	methodToTest := self class >> #methodWithDynamicArrayCreation.
	debugInfo := OldDebugInfo for: methodToTest.

	dynamicArrayNode := methodToTest ast statements first.
	sendInsideDynamicArrayNode := dynamicArrayNode statements first.
	self assert: sendInsideDynamicArrayNode isMessage.

	sendPC := (sendInsideDynamicArrayNode methodNode pcsForNode: sendInsideDynamicArrayNode) first.
	
	self assert: (debugInfo shouldStopAt: sendPC)
]

{ #category : 'tests - shouldStopAt' }
DebugInfoTest >> testStopAtSendInInlinedBlock [

	| debugInfo methodToTest todoSend sendInsideToDoBlock sendPC |
	methodToTest := self class >> #methodWithOptimizedSend.
	debugInfo := OldDebugInfo for: methodToTest.

	todoSend := methodToTest ast statements first.
	sendInsideToDoBlock := todoSend arguments second body statements first.
	self assert: sendInsideToDoBlock isMessage.
	sendPC := (sendInsideToDoBlock methodNode pcsForNode: sendInsideToDoBlock) first.
	
	self assert: (debugInfo shouldStopAt: sendPC)
]
